[package]
name = "jvertswag-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.26", features = ["derive"] }
regex = "1.11.1"
reqwest = "0.12.12"
serde = "1.0.217"
serde_json = "1.0.135"
tokio = "1.43.0"
